name: CI/CD Pipeline
on: [push]
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installiere NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Installiere Abhängigkeiten
      run: |
        cd backend
        npm install
    - name: Teste
      run: |
        cd backend
        npm test -- --detectOpenHandles --forceExit
  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installiere NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Installiere Abhängigkeiten
      run: |
        cd frontend
        npm install
    - name: Teste
      run: |
        cd frontend
        npm test -- --detectOpenHandles --forceExit    
